
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  >
        <AppRouterCacheProvider theme={theme}>
          <ThemeProvider theme={theme}>
          {children}
          </ThemeProvider>
        
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
